var appControllers = angular.module('appControllers', []);
$.loadScript('js/controllers/loginController.js');
$.loadScript('js/controllers/mainController.js');
$.loadScript('js/controllers/profileController.js');
$.loadScript('js/controllers/summaryController.js');
$.loadScript('js/controllers/experienceController.js');
$.loadScript('js/controllers/caredCausesController.js');
$.loadScript('js/controllers/supportedOrganizationController.js');
$.loadScript('js/controllers/skillsController.js');
$.loadScript('js/controllers/educationController.js');